### ISSUE TITLE
Fails on Fedora 24

### ISSUE THREAD

**Issue by johnpoth** [fabric8io-images/fish-pepper#11]
Fails on Fedora 24, problem seems to be related to nodegit (libcurl package is already installed):
```
$fish-pepper
/home/jpoth/.nvm/versions/node/v8.1.4/lib/node_modules/fish-pepper/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jpoth/.nvm/versions/node/v8.1.4/lib/node_modules/fish-pepper/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

```

**Comment by johnpoth** [comment]
As a quick fix to solve this on Fedora, create a symbolic link with name 'libcurl-gnutls.so.4' in your lib folder, in my case:

`sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
`
