### ISSUE TITLE
nodegit configure: error: No crypto library found!

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/fish-pepper#12]
Hello, I'm interested in contributing to https://github.com/fabric8io-images and gathered that one should not be touching the [generated Dockerfile](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/Dockerfile)s, but [the Dockerfile template](https://github.com/fabric8io-images/s2i/blob/master/java/templates/Dockerfile), and for this I guess I need to local install a working fish-pepper?

@rhuss FYI unfortunately this fails for me on Fedora 26 (beware, I'm a Node.js noob, so this means little, to me):

```
npm -g install fish-pepper

/home/vorburger/.npm-packages/bin/fish-pepper -> /home/vorburger/.npm-packages/lib/node_modules/fish-pepper/fish-pepper.js

> fibers@2.0.0 install /home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-48` exists; testing
Binary is fine; exiting

> nodegit@0.20.1 install /home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/openssl/openssl
/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/openssl/openssl' }
/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/openssl/openssl
/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/vendor/openssl/openssl' }
[               ...] - install: info lifecycle nodegit@0.20.1~install: Failed to exec install script
/home/vorburger/.npm-packages/lib
└── (empty)

npm ERR! Linux 4.15.4-200.fc26.x86_64
npm ERR! argv "/home/vorburger/bin/node-v6.9.2-linux-x64/bin/node" "/home/vorburger/bin/npm" "-g" "install" "fish-pepper"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.20.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.20.1 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vorburger/dev/LearnOpenShift/git/s2i/npm-debug.log
npm ERR! code 1
```

**Comment by vorburger** [comment]
Found https://github.com/nodegit/nodegit/issues/1246, but the workaround given there doesn't even help, tried:

    sudo dnf install curl libcurl libcurl-devel
    sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4

@rhuss any idea what one has to do to get this working?

**Comment by mojavelinux** [comment]
You're missing required libraries for compilation. Try installing libgit2-devel. That should give you everything you need.

The symlink is only helpful for the *runtime* part, once compilation is complete.

**Comment by vorburger** [comment]
> Try installing libgit2-devel. That should give you everything you need.

That did help (probably `openssl-devel` did the trick ?) for building it - thank you!

> The symlink is only helpful for the runtime part, once compilation is complete.

oh... right, now I get it; https://github.com/nodegit/nodegit/issues/1246 was confusing me; so this:

```
$ fish-pepper 

/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vorburger/.npm-packages/lib/node_modules/fish-pepper/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

gets fixed by:

    sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
    $ fish-pepper                                                      
    No images found.

Thanks; case closed! (I've deleted my comment on https://github.com/nodegit/nodegit/issues/1246 to avoid more confusion.)
