### ISSUE TITLE
Installation failed on Fedora 28

### ISSUE THREAD

**Issue by abkieling** [fabric8io-images/fish-pepper#13]
Installation failed on Fedora 28:

```
$ npm -g install fish-pepper
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
/home/akieling/.npm-global/bin/fish-pepper -> /home/akieling/.npm-global/lib/node_modules/fish-pepper/fish-pepper.js

> fibers@3.1.1 install /home/akieling/dev/projects/fish-pepper/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57-glibc` exists; testing
Binary is fine; exiting

> nodegit@0.20.1 install /home/akieling/dev/projects/fish-pepper/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/home/akieling/dev/projects/fish-pepper/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.20.1 postinstall /home/akieling/dev/projects/fish-pepper/node_modules/nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node "/home/akieling/dev/projects/fish-pepper/node_modules/nodegit/dist/nodegit.js"
/home/akieling/dev/projects/fish-pepper/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/akieling/dev/projects/fish-pepper/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/home/akieling/dev/projects/fish-pepper/node_modules/nodegit/dist/nodegit.js"' }
+ fish-pepper@0.5.9
added 190 packages from 161 contributors in 21.288s
```

**Comment by vorburger** [comment]
Oups. I'm not much of a NPM guy myself... can any one else help to fix this? @rhuss? May be @edewit?

PS: Just FYI & FTR fishpepper does actually run for me locally on Fedora 28, but I had it installed before I upgraded, so that's moot if a fresh installation fails; this obviously needs to be fixed so that anyone can contribute to https://github.com/fabric8io-images/s2i ...

**Comment by edewit** [comment]
@alexkieling you might need to install `curl`

if /usr/lib64/libcurl.so.4 exists, you can:
```
$ sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
```

**Comment by abkieling** [comment]
Thanks @edewit . That solves the issue. It would be good to add that information to the docs.

**Comment by vorburger** [comment]
> It would be good to add that information to the docs.

#14
