### ISSUE TITLE
install fish-pepper

### ISSUE THREAD

**Issue by Thomas131** [fabric8io-images/fish-pepper#23]
Hello!
I just searched for something like fish-pepper, found you.

Sadly I am unable to get fish-pepper working, neighter in a clean Linux Mint 19 VM with npm freshly installed, nor in a node:latest-container:
```bash
lm19_vm@lm19vm:~$ npm install fish-pepper
loadDep:tar → get         ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine fibers@5.0.0: wanted: {"node":">=10.0.0"} (current: {"node":"8.10.0"loadDep:tar → fetchAndSha ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine semver@7.3.2: wanted: {"node":">=10"} (current: {"node":"8.10.0","npnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
loadDep:tar → mapToRegist ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine tar@6.0.2: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm"npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
loadDep:tar               ▐ ╢██████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chownr@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","np
> fibers@5.0.0 install /home/lm19_vm/node_modules/fibers
> node build.js || nodejs build.js

make: Verzeichnis „/home/lm19_vm/node_modules/fibers/build“ wird betreten
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
fibers.target.mk:110: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Verzeichnis „/home/lm19_vm/node_modules/fibers/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lm19_vm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/home/lm19_vm/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/lm19_vm/node_modules/fibers
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
make: Verzeichnis „/home/lm19_vm/node_modules/fibers/build“ wird betreten
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
fibers.target.mk:110: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Verzeichnis „/home/lm19_vm/node_modules/fibers/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lm19_vm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/home/lm19_vm/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/lm19_vm/node_modules/fibers
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
/home/lm19_vm
├── colors@1.4.0 
├─┬ dockerode@3.2.1 
│ ├─┬ docker-modem@2.1.4 
│ │ ├─┬ debug@4.1.1 
│ │ │ └── ms@2.1.2 
│ │ ├─┬ readable-stream@3.6.0 
│ │ │ ├── string_decoder@1.3.0 
│ │ │ └── util-deprecate@1.0.2 
│ │ ├── split-ca@1.0.1 
│ │ └─┬ ssh2@0.8.9 
│ │   └─┬ ssh2-streams@0.4.10 
│ │     ├── asn1@0.2.4 
│ │     ├─┬ bcrypt-pbkdf@1.0.2 
│ │     │ └── tweetnacl@0.14.5 
│ │     └── streamsearch@0.1.2 
│ └─┬ tar-fs@2.0.1 
│   ├── chownr@1.1.4 
│   ├── mkdirp-classic@0.5.3 
│   ├─┬ pump@3.0.0 
│   │ └── end-of-stream@1.4.4 
│   └─┬ tar-stream@2.1.3 
│     ├─┬ bl@4.0.2 
│     │ └─┬ buffer@5.6.0 
│     │   ├── base64-js@1.3.1 
│     │   └── ieee754@1.1.13 
│     └── fs-constants@1.0.0 
├── dot@1.1.3 
├─┬ js-yaml@3.14.0 
│ ├─┬ argparse@1.0.10 
│ │ └── sprintf-js@1.0.3 
│ └── esprima@4.0.1 
├── node-getopt@0.3.2 
├─┬ nodegit@0.26.1 
│ ├─┬ fs-extra@7.0.1 
│ │ ├── graceful-fs@4.2.4 
│ │ ├── jsonfile@4.0.0 
│ │ └── universalify@0.1.2 
│ ├─┬ json5@2.1.3 
│ │ └── minimist@1.2.5 
│ ├── lodash@4.17.19 
│ ├── nan@2.14.1 
│ ├─┬ node-gyp@4.0.0 
│ │ ├── mkdirp@0.5.5 
│ │ ├─┬ nopt@3.0.6 
│ │ │ └── abbrev@1.1.1 
│ │ ├─┬ npmlog@2.0.4 
│ │ │ ├── ansi@0.3.1 
│ │ │ ├─┬ are-we-there-yet@1.1.5 
│ │ │ │ ├── delegates@1.0.0 
│ │ │ │ └─┬ readable-stream@2.3.7 
│ │ │ │   ├── safe-buffer@5.1.2 
│ │ │ │   └── string_decoder@1.1.1 
│ │ │ └─┬ gauge@1.2.7 
│ │ │   ├── has-unicode@2.0.1 
│ │ │   ├── lodash.pad@4.5.1 
│ │ │   ├── lodash.padend@4.6.1 
│ │ │   └── lodash.padstart@4.6.1 
│ │ ├─┬ osenv@0.1.5 
│ │ │ ├── os-homedir@1.0.2 
│ │ │ └── os-tmpdir@1.0.2 
│ │ ├─┬ request@2.88.2 
│ │ │ ├── aws-sign2@0.7.0 
│ │ │ ├── aws4@1.10.0 
│ │ │ ├── caseless@0.12.0 
│ │ │ ├─┬ combined-stream@1.0.8 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── extend@3.0.2 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@2.3.3 
│ │ │ │ └── asynckit@0.4.0 
│ │ │ ├─┬ har-validator@5.1.5 
│ │ │ │ ├─┬ ajv@6.12.3 
│ │ │ │ │ ├── fast-deep-equal@3.1.3 
│ │ │ │ │ ├── fast-json-stable-stringify@2.1.0 
│ │ │ │ │ ├── json-schema-traverse@0.4.1 
│ │ │ │ │ └── uri-js@4.2.2 
│ │ │ │ └── har-schema@2.0.0 
│ │ │ ├─┬ http-signature@1.2.0 
│ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ ├─┬ jsprim@1.4.1 
│ │ │ │ │ ├── extsprintf@1.3.0 
│ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ └── verror@1.10.0 
│ │ │ │ └─┬ sshpk@1.16.1 
│ │ │ │   ├── dashdash@1.14.1 
│ │ │ │   ├── ecc-jsbn@0.1.2 
│ │ │ │   ├── getpass@0.1.7 
│ │ │ │   └── jsbn@0.1.1 
│ │ │ ├── is-typedarray@1.0.0 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├─┬ mime-types@2.1.27 
│ │ │ │ └── mime-db@1.44.0 
│ │ │ ├── oauth-sign@0.9.0 
│ │ │ ├── performance-now@2.1.0 
│ │ │ ├── qs@6.5.2 
│ │ │ ├── tunnel-agent@0.6.0 
│ │ │ └── uuid@3.4.0 
│ │ ├── rimraf@2.7.1 
│ │ ├── semver@5.3.0 
│ │ ├─┬ tar@4.4.13 
│ │ │ ├── fs-minipass@1.2.7 
│ │ │ ├── minipass@2.9.0 
│ │ │ ├── minizlib@1.3.3 
│ │ │ ├── safe-buffer@5.2.1 
│ │ │ └── yallist@3.1.1 
│ │ └─┬ which@1.3.1 
│ │   └── isexe@2.0.0 
│ ├─┬ node-pre-gyp@0.13.0 
│ │ ├── detect-libc@1.0.3 
│ │ ├── mkdirp@0.5.5 
│ │ ├─┬ needle@2.5.0 
│ │ │ ├── debug@3.2.6 
│ │ │ ├─┬ iconv-lite@0.4.24 
│ │ │ │ └── safer-buffer@2.1.2 
│ │ │ └── sax@1.2.4 
│ │ ├── nopt@4.0.3 
│ │ ├─┬ npm-packlist@1.4.8 
│ │ │ ├── ignore-walk@3.0.3 
│ │ │ ├── npm-bundled@1.1.1 
│ │ │ └── npm-normalize-package-bin@1.0.1 
│ │ ├─┬ npmlog@4.1.2 
│ │ │ ├── console-control-strings@1.1.0 
│ │ │ ├─┬ gauge@2.7.4 
│ │ │ │ ├── aproba@1.2.0 
│ │ │ │ ├── object-assign@4.1.1 
│ │ │ │ ├── signal-exit@3.0.3 
│ │ │ │ ├─┬ string-width@1.0.2 
│ │ │ │ │ ├── code-point-at@1.1.0 
│ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│ │ │ │ │   └── number-is-nan@1.0.1 
│ │ │ │ ├─┬ strip-ansi@3.0.1 
│ │ │ │ │ └── ansi-regex@2.1.1 
│ │ │ │ └── wide-align@1.1.3 
│ │ │ └── set-blocking@2.0.0 
│ │ ├─┬ rc@1.2.8 
│ │ │ ├── deep-extend@0.6.0 
│ │ │ ├── ini@1.3.5 
│ │ │ └── strip-json-comments@2.0.1 
│ │ ├── rimraf@2.7.1 
│ │ ├── semver@5.7.1 
│ │ └── tar@4.4.13 
│ ├─┬ promisify-node@0.3.0 
│ │ └─┬ nodegit-promise@4.0.0 
│ │   └── asap@2.0.6 
│ ├── ramda@0.25.0 
│ ├─┬ request-promise-native@1.0.9 
│ │ ├── request-promise-core@1.1.4 
│ │ ├── stealthy-require@1.1.1 
│ │ └─┬ tough-cookie@2.5.0 
│ │   ├── psl@1.8.0 
│ │   └── punycode@2.1.1 
│ └─┬ tar-fs@1.16.3 
│   ├── mkdirp@0.5.5 
│   ├── pump@1.0.3 
│   └─┬ tar-stream@1.6.2 
│     ├── bl@1.2.2 
│     ├─┬ buffer-alloc@1.2.0 
│     │ ├── buffer-alloc-unsafe@1.1.0 
│     │ └── buffer-fill@1.0.0 
│     ├─┬ readable-stream@2.3.7 
│     │ ├── core-util-is@1.0.2 
│     │ ├── isarray@1.0.0 
│     │ ├── process-nextick-args@2.0.1 
│     │ ├── safe-buffer@5.1.2 
│     │ └─┬ string_decoder@1.1.1 
│     │   └── safe-buffer@5.1.2 
│     ├── to-buffer@1.1.1 
│     └── xtend@4.0.2 
├─┬ rimraf@3.0.2 
│ └─┬ glob@7.1.6 
│   ├── fs.realpath@1.0.0 
│   ├─┬ inflight@1.0.6 
│   │ └── wrappy@1.0.2 
│   ├── inherits@2.0.4 
│   ├─┬ minimatch@3.0.4 
│   │ └─┬ brace-expansion@1.1.11 
│   │   ├── balanced-match@1.0.0 
│   │   └── concat-map@0.0.1 
│   ├── once@1.4.0 
│   └── path-is-absolute@1.0.1 
├── semver@7.3.2 
└─┬ tar@6.0.2 
  ├── chownr@2.0.0 
  ├── fs-minipass@2.1.0 
  ├── minipass@3.1.3 
  ├── minizlib@2.1.0 
  ├── mkdirp@1.0.4 
  └── yallist@4.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/lm19_vm/package.json'
npm WARN lm19_vm No description
npm WARN lm19_vm No repository field.
npm WARN lm19_vm No README data
npm WARN lm19_vm No license field.
npm ERR! Linux 4.15.0-54-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "fish-pepper"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! fibers@5.0.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@5.0.0 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lm19_vm/npm-debug.log
lm19_vm@lm19vm:~$ 
```

Is fish-pepper maintained? Is there a more common way to template Dockerfiles?

Thanks in advance!
Thomas131

**Comment by Thomas131** [comment]
Oh, I just noticed your own fish-pepper container - it works! It seems that the only differences seems to be the node:lts and node:latest and the `npm config set unsafe-perm true`.

It still looks pretty abandoned with all the deprecated/unsupported libraries ...

**Comment by rhuss** [comment]
sorry, I dont have time or budget to maintain or extend fish-pepper in a substainable way. It's already quite aged (but still functional and used in the fabric8 images). 

For getting it on par with the latest node version quite some deps need to be updated, that's true. 

Said that I'm still happy to help to integrate PRs, but it could be that this project will be sunset in the near future if no one is taking it over.
